version: '3'

services:
    api:
        image: netflix-clone-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - "${API_PORT}:8080"
        volumes:
            - ./src/:/usr/src/app/src
        environment:
            API_PORT: ${API_PORT}
            NODE_ENV: development
            API_KEY: ${API_KEY}
            BASE_URL: ${BASE_URL}
